In [1]:
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:
	import numpy as np 
	B = np.array(B)
	C = np.array(C)
	C_inv = np.linalg.inv(C)
	P = C_inv @ B
	return P

In [2]:
B = [[1, 0, 0], 
    [0, 1, 0], 
    [0, 0, 1]]
C = [[1, 2.3, 3], 
    [4.4, 25, 6], 
    [7.4, 8, 9]]

output= [[-0.6772, -0.0126, 0.2342],
        [-0.0184, 0.0505, -0.0275],
        [0.5732, -0.0345, -0.0569]]

my_output = transform_basis(B, C)

import numpy as np

assert np.allclose(output, my_output.tolist(), atol=1e-4)

# SciPy Check

In [3]:
from scipy import linalg
scipy_ouput = linalg.solve(C, B)
print(scipy_ouput)

assert np.allclose(output, scipy_ouput, atol=1e-4)

[[-0.67722681 -0.01262626  0.23415978]
 [-0.01836547  0.05050505 -0.02754821]
 [ 0.5731558  -0.03451178 -0.05693297]]
