In [5]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    #Write your code here and return a python list after reshaping by using numpy's tolist() method
    reshaped_matrix = np.array(a).reshape(new_shape).tolist()
    return reshaped_matrix

In [6]:
a = [[1,2,3,4],[5,6,7,8]]
new_shape = (4, 2)
output = [[1, 2], [3, 4], [5, 6], [7, 8]]

my_output = reshape_matrix(output, new_shape)

assert output == my_output

In [11]:
np.array(a)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
# ‘C’ means to read / write the elements using C-like index order, 
# with the last axis index changing fastest, back to the first axis index changing slowest.
np.array(a).reshape(new_shape).tolist() # C-like index ordering

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [13]:
# You can think of reshaping as first raveling the array (using the given index order), 
# then inserting the elements from the raveled array into the new array using the same kind of index ordering as was used for the raveling.
np.ravel(a, 'F')

array([1, 5, 2, 6, 3, 7, 4, 8])

In [10]:
# ‘F’ means to read / write the elements using Fortran-like index order, 
# with the first index changing fastest, and the last index changing slowest.
#  reshapes arrays by filling the new array column by column.
np.array(a).reshape(new_shape, order='F').tolist() # Fortran-like index ordering

[[1, 3], [5, 7], [2, 4], [6, 8]]