In [8]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    n_row, n_col = len(matrix), len(matrix[0])
    if mode == 'column':
        means = [
            sum(matrix[i][j] for i in range(n_row)) / n_row
            for j in range(n_col)
        ]

        # [sum(col) / len(matrix) for col in zip(*matrix)]
    elif mode == 'row':
        means = [
            sum(matrix[i][j] for j in range(n_col)) / n_col
            for i in range(n_row) 
        ]
    else:
        raise ValueError(f"Mode {mode} invalid!")
    return means

In [9]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mode = 'column'
output = [4.0, 5.0, 6.0]

my_output = calculate_matrix_mean(matrix, mode)
assert output == my_output

In [10]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mode = 'row'
output = [2.0, 5.0, 8.0]

my_output = calculate_matrix_mean(matrix, mode)
assert output == my_output

In [14]:
import numpy as np

# sum by col (along the first dim, which is along col) 
print(np.array(matrix).mean(axis=0))

# sum by row (along the second dim, which is along row) 
print(np.array(matrix).mean(axis=1))


[4. 5. 6.]
[2. 5. 8.]


In [15]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])